from fastapi import HTTPException


def question2(tasks):
    pass


def question3(tasks):
    pass


def question4(tasks):
    pass


def question5(tasks, task_id: int):
    pass


def question6(tasks, query: str):
    pass


def question7(tasks):
    pass


def question8(tasks, criteria: dict, sort_by: str):
    
    raise HTTPException(status_code=401, detail="For this task, 8, you are expected to solve it using SQLAlchemy. Please don't use this function, and return the result directly from the ")


def question9(tasks, worker_threads: int):
    pass